/**
 * GET  /api/links?type=company&id=12345678 — hent links for en entitet
 * POST /api/links — opret eller verificer et link
 *
 * Håndterer crowdsourced link-verificering for virksomheder og personer.
 * Links gemmes i Supabase (verified_links + link_verifications).
 * Fallback til auto-genererede links hvis Supabase ikke er tilgængelig.
 *
 * @param type - 'company' eller 'person'
 * @param id - CVR-nummer (company) eller enhedsNummer (person)
 */

import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { createClient } from '@supabase/supabase-js';
import { parseBody } from '@/app/lib/validate';
import { writeAuditLog } from '@/app/lib/auditLog';

/** Zod schema for POST /api/links request body */
const linksPostSchema = z
  .object({
    action: z.string().optional(),
    userId: z.string().min(1),
  })
  .passthrough();

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ?? '';

/** Platform config med ikoner og URL-patterns */
export interface PlatformConfig {
  platform: string;
  label: string;
  icon: string;
  color: string;
  searchUrl: (name: string, extra?: string) => string;
}

export const PLATFORMS: PlatformConfig[] = [
  {
    platform: 'website',
    label: 'Hjemmeside',
    icon: '🌐',
    color: 'text-blue-400',
    searchUrl: (name) => `https://www.google.com/search?q=${encodeURIComponent(name)}+hjemmeside`,
  },
  {
    platform: 'linkedin',
    label: 'LinkedIn',
    icon: 'linkedin',
    color: 'text-[#0A66C2]',
    searchUrl: (name, type) =>
      type === 'person'
        ? `https://www.linkedin.com/search/results/people/?keywords=${encodeURIComponent(name)}`
        : `https://www.linkedin.com/search/results/companies/?keywords=${encodeURIComponent(name)}`,
  },
  {
    platform: 'facebook',
    label: 'Facebook',
    icon: 'facebook',
    color: 'text-[#1877F2]',
    searchUrl: (name, type) =>
      type === 'person'
        ? `https://www.facebook.com/search/people/?q=${encodeURIComponent(name)}`
        : `https://www.facebook.com/search/pages/?q=${encodeURIComponent(name)}`,
  },
  {
    platform: 'instagram',
    label: 'Instagram',
    icon: 'instagram',
    color: 'text-[#E4405F]',
    searchUrl: (name) =>
      `https://www.google.com/search?q=${encodeURIComponent(name)}+instagram.com`,
  },
  {
    platform: 'twitter',
    label: 'X / Twitter',
    icon: 'twitter',
    color: 'text-slate-300',
    searchUrl: (name) =>
      `https://www.google.com/search?q=${encodeURIComponent(name)}+site:x.com+OR+site:twitter.com`,
  },
];

/** Company-specific platforms */
export const COMPANY_PLATFORMS: PlatformConfig[] = [
  ...PLATFORMS,
  {
    platform: 'virk',
    label: 'Virk.dk (CVR)',
    icon: 'virk',
    color: 'text-emerald-400',
    searchUrl: (_, cvr) => `https://datacvr.virk.dk/enhed/virksomhed/${cvr}`,
  },
];

export interface LinkData {
  id: string | null;
  platform: string;
  label: string;
  icon: string;
  color: string;
  url: string;
  verifyCount: number;
  userVerified: boolean;
  isAutoGenerated: boolean;
}

// ─── GET: Hent links for en entitet ─────────────────────────────────────────

export async function GET(req: NextRequest) {
  const entityType = req.nextUrl.searchParams.get('type') ?? '';
  const entityId = req.nextUrl.searchParams.get('id') ?? '';
  const entityName = req.nextUrl.searchParams.get('name') ?? '';
  const userId = req.nextUrl.searchParams.get('userId') ?? '';

  if (!entityType || !entityId) {
    return NextResponse.json({ error: 'type og id er påkrævet' }, { status: 400 });
  }

  const platforms = entityType === 'company' ? COMPANY_PLATFORMS : PLATFORMS;
  const links: LinkData[] = [];

  // Forsøg at hente fra Supabase
  let dbLinks: Record<string, unknown>[] = [];
  let userVerifications = new Set<string>();

  if (SUPABASE_URL && SUPABASE_SERVICE_KEY) {
    try {
      const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

      // Hent alle links for denne entitet
      const { data: savedLinks } = await supabase
        .from('verified_links')
        .select('*')
        .eq('entity_type', entityType)
        .eq('entity_id', entityId);

      dbLinks = savedLinks ?? [];

      // Hent brugerens verifikationer
      if (userId && dbLinks.length > 0) {
        const linkIds = dbLinks.map((l) => l.id as string);
        const { data: verifications } = await supabase
          .from('link_verifications')
          .select('link_id')
          .eq('user_id', userId)
          .in('link_id', linkIds);

        userVerifications = new Set((verifications ?? []).map((v) => v.link_id as string));
      }
    } catch {
      // Supabase ikke tilgængelig — brug auto-genererede links
    }
  }

  // Byg links for hver platform
  for (const p of platforms) {
    // Find gemte links for denne platform
    const savedForPlatform = dbLinks.filter((l) => l.platform === p.platform);

    if (savedForPlatform.length > 0) {
      // Brug gemte links (kan have flere per platform)
      for (const saved of savedForPlatform) {
        links.push({
          id: saved.id as string,
          platform: p.platform,
          label: p.label,
          icon: p.icon,
          color: p.color,
          url: saved.url as string,
          verifyCount: (saved.verify_count as number) ?? 0,
          userVerified: userVerifications.has(saved.id as string),
          isAutoGenerated: false,
        });
      }
    } else {
      // Auto-generér søge-link
      const _extra = entityType === 'company' ? entityId : undefined;
      const autoUrl =
        p.platform === 'virk'
          ? p.searchUrl(entityName, String(entityId).padStart(8, '0'))
          : p.searchUrl(entityName, entityType);

      links.push({
        id: null,
        platform: p.platform,
        label: p.label,
        icon: p.icon,
        color: p.color,
        url: autoUrl,
        verifyCount: 0,
        userVerified: false,
        isAutoGenerated: true,
      });
    }
  }

  return NextResponse.json(links);
}

// ─── POST: Opret link eller verificer eksisterende ──────────────────────────

export async function POST(req: NextRequest) {
  if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
    return NextResponse.json({ error: 'Supabase ikke konfigureret' }, { status: 503 });
  }

  const parsed = await parseBody(req, linksPostSchema);
  if (!parsed.success) return parsed.response;
  const { action, userId } = parsed.data;
  const { entityType, entityId, entityName, platform, url, linkId } = parsed.data as Record<
    string,
    string | undefined
  >;

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

  // ── Verificer et eksisterende link ──
  if (action === 'verify' && linkId) {
    // Check om brugeren allerede har verificeret
    const { data: existing } = await supabase
      .from('link_verifications')
      .select('id')
      .eq('link_id', linkId)
      .eq('user_id', userId)
      .maybeSingle();

    if (existing) {
      return NextResponse.json({ error: 'Allerede verificeret' }, { status: 409 });
    }

    // Tilføj verifikation
    const { error: insertErr } = await supabase
      .from('link_verifications')
      .insert({ link_id: linkId, user_id: userId });

    if (insertErr) {
      console.error('[links] insert link_verifications fejl:', insertErr.message);
      const body =
        process.env.NODE_ENV === 'development'
          ? { error: 'Intern serverfejl', dev_detail: insertErr.message }
          : { error: 'Intern serverfejl' };
      return NextResponse.json(body, { status: 500 });
    }

    // Opdater verify_count
    const { error: updateErr } = await supabase.rpc('increment_verify_count', {
      p_link_id: linkId,
    });
    // Fallback hvis RPC ikke eksisterer
    if (updateErr) {
      await supabase
        .from('verified_links')
        .update({
          verify_count: 1,
          updated_at: new Date().toISOString(),
        })
        .eq('id', linkId);
    }

    // Audit: link verified (fire-and-forget — ISO 27001 A.12.4)
    void writeAuditLog({
      action: 'link_verified',
      resource_type: 'link',
      resource_id: linkId,
      metadata: JSON.stringify({ user_id: userId }),
    });

    return NextResponse.json({ success: true });
  }

  // ── Tilføj et nyt link (fra auto-genereret til verificeret) ──
  if (action === 'add' && entityType && entityId && platform && url) {
    // Upsert — hvis linket allerede eksisterer, returner det
    const { data: existing } = await supabase
      .from('verified_links')
      .select('id')
      .eq('entity_type', entityType)
      .eq('entity_id', entityId)
      .eq('platform', platform)
      .eq('url', url)
      .maybeSingle();

    let linkIdToVerify: string;

    if (existing) {
      linkIdToVerify = existing.id;
    } else {
      const { data: inserted, error: insertErr } = await supabase
        .from('verified_links')
        .insert({
          entity_type: entityType,
          entity_id: entityId,
          entity_name: entityName ?? '',
          platform,
          url,
          verify_count: 1,
        })
        .select('id')
        .single();

      if (insertErr || !inserted) {
        console.error('[links] insert verified_links fejl:', insertErr?.message ?? 'Insert failed');
        const body =
          process.env.NODE_ENV === 'development'
            ? { error: 'Intern serverfejl', dev_detail: insertErr?.message ?? 'Insert failed' }
            : { error: 'Intern serverfejl' };
        return NextResponse.json(body, { status: 500 });
      }
      linkIdToVerify = inserted.id;
    }

    // Registrer brugerens verifikation
    await supabase
      .from('link_verifications')
      .insert({ link_id: linkIdToVerify, user_id: userId })
      .single();

    // Opdater count
    const { data: countData } = await supabase
      .from('link_verifications')
      .select('id')
      .eq('link_id', linkIdToVerify);

    await supabase
      .from('verified_links')
      .update({ verify_count: countData?.length ?? 1, updated_at: new Date().toISOString() })
      .eq('id', linkIdToVerify);

    // Audit: link verified after add (fire-and-forget — ISO 27001 A.12.4)
    void writeAuditLog({
      action: 'link_verified',
      resource_type: 'link',
      resource_id: linkIdToVerify,
      metadata: JSON.stringify({
        user_id: userId,
        platform,
        entity_type: entityType,
        entity_id: entityId,
      }),
    });

    return NextResponse.json({ success: true, linkId: linkIdToVerify });
  }

  return NextResponse.json({ error: 'Ugyldig action' }, { status: 400 });
}
