#!/usr/bin/env node
/**
 * BizzAssist local development seed script.
 *
 * Prints sample SQL INSERT statements and instructions for seeding a local
 * Supabase instance with placeholder development data.
 *
 * Does NOT execute SQL directly — copy the statements below into the
 * Supabase Dashboard SQL editor, or pipe to `supabase db execute`.
 *
 * Sample data includes:
 *   - One test tenant (organisation)
 *   - One test user linked to that tenant
 *   - One test saved entity (property)
 *
 * NEVER run against production — all IDs and values are placeholders.
 *
 * Usage:
 *   node scripts/seed.js
 */

const DIVIDER = '─'.repeat(60);

console.log(DIVIDER);
console.log('  BizzAssist — Local Dev Seed Script');
console.log(DIVIDER);
console.log('\n  This script prints sample SQL for local development only.');
console.log('  Copy into Supabase Dashboard → SQL Editor, or run:\n');
console.log('    supabase db execute < scripts/seed.sql\n');
console.log(DIVIDER);

const tenantId = '00000000-0000-0000-0000-000000000001';
const userId = '00000000-0000-0000-0000-000000000002';

const sql = `
-- ============================================================
--  BizzAssist local dev seed data
--  Generated by scripts/seed.js — DO NOT use in production
-- ============================================================

-- 1. Test tenant (organisation)
INSERT INTO public.organisations (id, name, slug, plan, created_at)
VALUES (
  '${tenantId}',
  'Test Organisation ApS',
  'test-organisation',
  'pro',
  NOW()
)
ON CONFLICT (id) DO NOTHING;

-- 2. Test user profile linked to the tenant
--    The auth.users row must already exist (created via Supabase Auth signup
--    or the Supabase Dashboard → Authentication → Users → "Add user").
INSERT INTO public.user_profiles (id, tenant_id, full_name, role, created_at)
VALUES (
  '${userId}',
  '${tenantId}',
  'Test Bruger',
  'admin',
  NOW()
)
ON CONFLICT (id) DO NOTHING;

-- 3. One saved entity (followed property) for the test tenant
INSERT INTO public.saved_entities (
  id,
  tenant_id,
  entity_type,
  entity_id,
  label,
  is_monitored,
  created_at
)
VALUES (
  gen_random_uuid(),
  '${tenantId}',
  'property',
  '1234567',
  'Testvej 1, 2650 Hvidovre',
  false,
  NOW()
)
ON CONFLICT DO NOTHING;

-- ============================================================
--  Done. Log in with the test user to verify the seed data.
-- ============================================================
`;

console.log('\n  SAMPLE SQL:\n');
console.log(sql);
console.log(DIVIDER);
console.log('\n  NOTES\n');
console.log('  - tenant_id:  ' + tenantId + '  (placeholder)');
console.log('  - user_id:    ' + userId + '  (placeholder)');
console.log('  - Create the auth.users row first in Supabase Dashboard');
console.log('    → Authentication → Users → "Add user"');
console.log('    Use the same UUID (' + userId + ') for the user ID.\n');
console.log('  - After seeding, start the dev server:');
console.log('    npm run dev\n');
console.log('  - Log in with the test user credentials you set above.\n');
console.log(DIVIDER + '\n');
